name: Scraping SBS Diario

on:
  # schedule:
  #  - cron: '0 17 * * *'  # Se ejecuta todos los días a las 12:00 hora Perú (5:00 UTC)
  workflow_dispatch:     # Permite ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
            
      - name: Ejecutar scraping
        run: python sbs_scraping.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Autenticarse con PAT y hacer push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/Tilin1136/ScrapSBSRetasas.git
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          git diff --cached --quiet || (
            git commit -m "Datos actualizados automáticamente al $(date '+%d-%m-%Y %H:%M')"
            git push origin main
          )
